export const OPEN_WEB_PUSH_NOTIFY = "OPEN_WEB_PUSH_NOTIFY";
export const SET_DEVICE_ID = "SET_DEVICE_ID";

// Instant
export const instantActionsTypes = {
  SET_INSTANT_ORDER: "SET_INSTANT_ORDER",
  CURRENT_INSTANT_ORDER: "CURRENT_INSTANT_ORDER",
};

// Order
export const orderActionsTypes = {
  SET_ORDER_DATA: "SET_ORDER_DATA",
};

// Account
export const accountActionsTypes = {
  // Set
  SET_CURRENT_ACC_BEGIN: "SET_CURRENT_ACC_BEGIN",
  SET_CURRENT_ACC_SUCCESS: "SET_CURRENT_ACC_SUCCESS",
  SET_CURRENT_ACC_ERROR: "SET_CURRENT_ACC_ERROR",
  SET_CURRENT_ACC_CLEAR: "SET_CURRENT_ACC_CLEAR",

  // Get
  GET_CURRENT_ACC_BEGIN: "GET_CURRENT_ACC_BEGIN",
  GET_CURRENT_ACC_SUCCESS: "GET_CURRENT_ACC_SUCCESS",
  GET_CURRENT_ACC_ERROR: "GET_CURRENT_ACC_ERROR",
  GET_CURRENT_ACC_CLEAR: "GET_CURRENT_ACC_CLEAR",

  // History
  SET_HISTORY_ACC_BEGIN: "SET_HISTORY_ACC_BEGIN",
  SET_HISTORY_ACC_SUCCESS: "SET_HISTORY_ACC_SUCCESS",
  SET_HISTORY_ACC_ERROR: "SET_HISTORY_ACC_ERROR",
  SET_HISTORY_ACC_CLEAR: "SET_HISTORY_ACC_CLEAR",
};

// Expired Order
export const expiredActionTypes = {
  SET_EXPIRED_BEGIN: "SET_EXPIRED_BEGIN",
  SET_EXPIRED_SUCCESS: "SET_EXPIRED_SUCCESS",
  SET_EXPIRED_ERROR: "SET_EXPIRED_ERROR",
  SET_EXPIRED_CLEAR: "SET_EXPIRED_CLEAR",
};

// Auto Pickup
export const autoPickActionTypes = {
  SET_AUTO_PICK_BEGIN: "SET_AUTO_PICK_BEGIN",
  SET_AUTO_PICK_SUCCESS: "SET_AUTO_PICK_SUCCESS",
  SET_AUTO_PICK_ERROR: "SET_AUTO_PICK_ERROR",
  SET_AUTO_PICK_CLEAR: "SET_AUTO_PICK_CLEAR",
};

// Bank Form
export const bankFormActionsTypes = {
  SET_BUY_FORM: "SET_BUY_FORM",
  SET_SELL_FORM: "SET_SELL_FORM",
};

// Member Chat
export const memberChatActionsTypes = {
  SHOW_CHAT: "[member-chat]: SET_SHOW_CHAT",
  SET_MESSAGE_LIST: "[member-chat]: SET_MESSAGE_LIST",
  SET_MESSAGE: "[member-chat]: SET_MESSAGE",
};

// Kyc
export const kycActionsTypes = {
  SET_KYC_BEGIN: "SET_KYC_BEGIN",
  SET_KYC_SUCCESS: "SET_KYC_SUCCESS",
  SET_KYC_ERROR: "SET_KYC_ERROR",
  SET_KYC_CLEAR: "SET_KYC_CLEAR",

  GET_KYC_BEGIN: "GET_KYC_BEGIN",
  GET_KYC_SUCCESS: "GET_KYC_SUCCESS",
  GET_KYC_ERROR: "GET_KYC_ERROR",
  GET_KYC_CLEAR: "GET_KYC_CLEAR",

  REMOVE_KYC_BEGIN: "REMOVE_KYC_BEGIN",
  REMOVE_KYC_SUCCESS: "REMOVE_KYC_SUCCESS",
  REMOVE_KYC_ERROR: "REMOVE_KYC_ERROR",
  REMOVE_KYC_CLEAR: "REMOVE_KYC_CLEAR",
};
