export const OPEN_WEB_PUSH_NOTIFY = "OPEN_WEB_PUSH_NOTIFY";
export const SET_DEVICE_ID = "SET_DEVICE_ID";

// Instant
export const instantActionsTypes = {
  SET_INSTANT_ORDER: "SET_INSTANT_ORDER",
  CURRENT_INSTANT_ORDER: "CURRENT_INSTANT_ORDER",
};

// Order
export const orderActionsTypes = {
  SET_ORDER_DATA: "SET_ORDER_DATA",
};

// Account
export const accountActionsTypes = {
  // Set
  SET_CURRENT_ACC_BEGIN: "SET_CURRENT_ACC_BEGIN",
  SET_CURRENT_ACC_SUCCESS: "SET_CURRENT_ACC_SUCCESS",
  SET_CURRENT_ACC_ERROR: "SET_CURRENT_ACC_ERROR",
  SET_CURRENT_ACC_CLEAR: "SET_CURRENT_ACC_CLEAR",

  // Get
  GET_CURRENT_ACC_BEGIN: "GET_CURRENT_ACC_BEGIN",
  GET_CURRENT_ACC_SUCCESS: "GET_CURRENT_ACC_SUCCESS",
  GET_CURRENT_ACC_ERROR: "GET_CURRENT_ACC_ERROR",
  GET_CURRENT_ACC_CLEAR: "GET_CURRENT_ACC_CLEAR",

  // History
  SET_HISTORY_ACC_BEGIN: "SET_HISTORY_ACC_BEGIN",
  SET_HISTORY_ACC_SUCCESS: "SET_HISTORY_ACC_SUCCESS",
  SET_HISTORY_ACC_ERROR: "SET_HISTORY_ACC_ERROR",
  SET_HISTORY_ACC_CLEAR: "SET_HISTORY_ACC_CLEAR",
};

// Expired Order
export const expiredActionTypes = {
  SET_EXPIRED_BEGIN: "SET_EXPIRED_BEGIN",
  SET_EXPIRED_SUCCESS: "SET_EXPIRED_SUCCESS",
  SET_EXPIRED_ERROR: "SET_EXPIRED_ERROR",
  SET_EXPIRED_CLEAR: "SET_EXPIRED_CLEAR",
};

// Auto Pickup
export const autoPickActionTypes = {
  SET_AUTO_PICK_BEGIN: "SET_AUTO_PICK_BEGIN",
  SET_AUTO_PICK_SUCCESS: "SET_AUTO_PICK_SUCCESS",
  SET_AUTO_PICK_ERROR: "SET_AUTO_PICK_ERROR",
  SET_AUTO_PICK_CLEAR: "SET_AUTO_PICK_CLEAR",
};
