// Sell
export const SET_RMB_SELL_RATE = 'SET_RMB_SELL_RATE';
export const SET_ORDER_TOKEN = 'SET_ORDER_TOKEN';
export const SET_WS_PAIRING = 'SET_WS_PAIRING';
export const SET_WS_DATA = 'SET_WS_DATA';
export const SET_SELL_COMPLETED = 'SET_SELL_COMPLETED';
export const SET_PAYMENT = 'SET_PAYMENT';
export const CLEAN_ORDER_TOKEN = 'CLEAN_ORDER_TOKEN';
export const SET_WS_CLIENT = 'SET_WS_CLIENT';
export const SET_CANCEL_ORDER_DATA = 'SET_CANCEL_ORDER_DATA';
export const SET_CONFIRM_SELL = 'SET_CONFIRM_SELL';

// Transfer
export const SET_TRANSFER_ORDER_TOKEN = 'SET_TRANSFER_ORDER_TOKEN';
export const SET_TRANSFER_STATUS = 'SET_TRANSFER_STATUS';
export const SET_USDT_COUNT = 'SET_USDT_COUNT';
export const SET_ORDER_DETAIL = 'SET_ORDER_DETAIL';
export const GET_WS_CLIENT = 'GET_WS_CLIENT';
export const HANDLE_BTN_LOADING = 'HANDLE_BTN_LOADING';
export const SET_TRANSFER_ERROR_TEXT = 'SET_TRANSFER_ERROR_TEXT';

// Balance
export const SET_BALANCE = 'GET_BALANCE';

// Chat
export const SET_TRANSLATE = 'SET_TRANSLATE';

// Auth
export const IS_SEND_VALID_CODE = 'IS_SEND_VALID_CODE'; // 簡訊驗證碼發送情況
export const SET_VALID_TOKEN = 'SET_VALID_TOKEN'; // 確認驗證碼正確後回傳的token
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SHOW_ERROR_MODAL = 'SHOW_ERROR_MODAL';
export const REMOVE_VALID_TOKEN = 'REMOVE_VALID_TOKEN';
export const SET_EXPIRED_TIME = 'SET_EXPIRED_TIME';

// History
export const SET_ALL_HISTORY = 'SET_ALL_HISTORY';
export const SET_SINGLE_DETAIL = 'SET_SINGLE_DETAIL';
export const SET_WAIT_HISTORY = 'SET_WAIT_HISTORY';

// Login
export const LOGIN_SET_LOADING = 'LOGIN_SET_LOADING';
export const SET_ERROR_TEXT = 'SET_ERROR_TEXT';

// Http Error
export const SET_HTTP_ERROR = 'SET_HTTP_ERROR';

// Buy
export const BUY_BTN_LOADING = 'BUY_BTN_LOADING';
export const SET_BUY_COUNT = 'SET_BUY_COUNT';
export const SET_BUY_ERROR_TEXT = 'SET_BUY_ERROR_TEXT';
export const SET_BUY_ORDER_TOKEN = 'SET_BUY_ORDER_TOKEN';
export const SET_BUY_WS_STATUS = 'SET_BUY_WS_STATUS';
export const HANDLE_PAIRING = 'HANDLE_PAIRING';
export const SET_SHOW_BANK = 'SET_SHOW_BANK';
export const SET_BUY_WS_CLIENT = 'SET_BUY_WS_CLIENT';
export const SET_BUY_WS_DATA = 'SET_BUY_WS_DATA';
export const SET_DELTA_TIME = 'SET_DELTA_TIME';
export const HIDE_BUY_INFO = 'HIDE_BUY_INFO';
